// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf9syUK5lg8Q9wberRhPNjxZTzdg0YWpY',
    appId: '1:1069895383899:web:a1b395552ba8b4fca3387e',
    messagingSenderId: '1069895383899',
    projectId: 'sober-steps-fire',
    authDomain: 'sober-steps-fire.firebaseapp.com',
    storageBucket: 'sober-steps-fire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM5nqsj0p_ERobW29xAQmJostvFaUwFJc',
    appId: '1:1069895383899:android:dd11ff7a4e828e15a3387e',
    messagingSenderId: '1069895383899',
    projectId: 'sober-steps-fire',
    storageBucket: 'sober-steps-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwgnKCe2TVrgIJ6bvBieqtLZXrtCtWBs',
    appId: '1:1069895383899:ios:2bf49dd1b7859b6ba3387e',
    messagingSenderId: '1069895383899',
    projectId: 'sober-steps-fire',
    storageBucket: 'sober-steps-fire.appspot.com',
    iosBundleId: 'com.tammeir.group.soberSteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOwgnKCe2TVrgIJ6bvBieqtLZXrtCtWBs',
    appId: '1:1069895383899:ios:d7e9f80901a192d3a3387e',
    messagingSenderId: '1069895383899',
    projectId: 'sober-steps-fire',
    storageBucket: 'sober-steps-fire.appspot.com',
    iosBundleId: 'com.tammeir.group.soberSteps.RunnerTests',
  );
}
